name: Java
on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 22
              uses: actions/setup-java@v2
              with:
                  distribution: 'adopt'
                  java-version: '22'
            - name: Build with Maven
              run: mvn -B package -DskipTests --file pom.xml
            - name: Run tests
              run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
                  - name: Report
                    uses: dorny/test-reporter@v1
                    if: always()
                    with:
                      name: Maven Tests
                      path: target/surefire-reports/*.xml
                      reporter: java-junit
                      fail-on-error: true
